import type { SimulatedQuote } from "./router";

export const DEMO_LIQUIDITY_BOOK: SimulatedQuote[] = [
  {
    quoteId: "france-a",
    venueId: "venue-alpha",
    venueLabel: "Simulated Venue A",
    outcomeId: "participant_1",
    decimalOdds: 2.76,
    availableStake: 1200,
  },
  {
    quoteId: "france-b",
    venueId: "venue-beta",
    venueLabel: "Simulated Venue B",
    outcomeId: "participant_1",
    decimalOdds: 2.7,
    availableStake: 1800,
  },
  {
    quoteId: "france-c",
    venueId: "venue-gamma",
    venueLabel: "Simulated Venue C",
    outcomeId: "participant_1",
    decimalOdds: 2.62,
    availableStake: 2200,
  },
  {
    quoteId: "draw-a",
    venueId: "venue-alpha",
    venueLabel: "Simulated Venue A",
    outcomeId: "draw",
    decimalOdds: 3.2,
    availableStake: 900,
  },
  {
    quoteId: "draw-b",
    venueId: "venue-beta",
    venueLabel: "Simulated Venue B",
    outcomeId: "draw",
    decimalOdds: 3.14,
    availableStake: 1600,
  },
  {
    quoteId: "draw-c",
    venueId: "venue-gamma",
    venueLabel: "Simulated Venue C",
    outcomeId: "draw",
    decimalOdds: 3.05,
    availableStake: 2500,
  },
  {
    quoteId: "spain-a",
    venueId: "venue-alpha",
    venueLabel: "Simulated Venue A",
    outcomeId: "participant_2",
    decimalOdds: 3.5,
    availableStake: 500,
  },
  {
    quoteId: "spain-b",
    venueId: "venue-beta",
    venueLabel: "Simulated Venue B",
    outcomeId: "participant_2",
    decimalOdds: 3.42,
    availableStake: 2000,
  },
  {
    quoteId: "spain-c",
    venueId: "venue-gamma",
    venueLabel: "Simulated Venue C",
    outcomeId: "participant_2",
    decimalOdds: 3.3,
    availableStake: 2500,
  },
  {
    quoteId: "spain-d",
    venueId: "venue-delta",
    venueLabel: "Simulated Venue D",
    outcomeId: "participant_2",
    decimalOdds: 2.1,
    availableStake: 5000,
  },
];