import type { SimulatedQuote } from "./router";

export const DEMO_LIQUIDITY_BOOK: SimulatedQuote[] = [
  {
    quoteId: "france-a",
    venueId: "matchbook",
    venueLabel: "Matchbook",
    outcomeId: "participant_1",
    decimalOdds: 2.72,
    availableStake: 1200,
  },
  {
    quoteId: "france-b",
    venueId: "pinnacle",
    venueLabel: "Pinnacle",
    outcomeId: "participant_1",
    decimalOdds: 2.6,
    availableStake: 1800,
  },
  {
    quoteId: "france-c",
    venueId: "william-hill",
    venueLabel: "William Hill",
    outcomeId: "participant_1",
    decimalOdds: 2.38,
    availableStake: 2200,
  },
  {
    quoteId: "draw-a",
    venueId: "matchbook",
    venueLabel: "Matchbook",
    outcomeId: "draw",
    decimalOdds: 3,
    availableStake: 900,
  },
  {
    quoteId: "draw-b",
    venueId: "pinnacle",
    venueLabel: "Pinnacle",
    outcomeId: "draw",
    decimalOdds: 3.03,
    availableStake: 1600,
  },
  {
    quoteId: "draw-c",
    venueId: "william-hill",
    venueLabel: "William Hill",
    outcomeId: "draw",
    decimalOdds: 3.1,
    availableStake: 2500,
  },
  {
    quoteId: "spain-a",
    venueId: "matchbook",
    venueLabel: "Matchbook",
    outcomeId: "participant_2",
    decimalOdds: 3.25,
    availableStake: 500,
  },
  {
    quoteId: "spain-b",
    venueId: "pinnacle",
    venueLabel: "Pinnacle",
    outcomeId: "participant_2",
    decimalOdds: 3.23,
    availableStake: 2000,
  },
  {
    quoteId: "spain-c",
    venueId: "william-hill",
    venueLabel: "William Hill",
    outcomeId: "participant_2",
    decimalOdds: 3,
    availableStake: 2500,
  },
  {
    quoteId: "spain-d",
    venueId: "policy-stress-quote",
    venueLabel: "Policy stress quote",
    outcomeId: "participant_2",
    decimalOdds: 2.1,
    availableStake: 5000,
  },
];
